"""empty message

Revision ID: d47f3759d571
Revises: 02b685e9228d
Create Date: 2024-06-19 08:38:22.916062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47f3759d571'
down_revision = '02b685e9228d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
